from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from typing import List
import uuid

from app.db import get_db
from app.api.deps import get_current_user
from app.models.campaign import (
    Campaign, Persona, CompetitorInsight, Angle, Hook, Headline,
    CTA, AdCopy, CreativeConcept, VideoScript, CampaignScore
)
from app.schemas.campaign import CampaignCreate, CampaignOut, CampaignFullOut
from app.workers.celery_app import generate_full_campaign

router = APIRouter()

@router.post("/analyze", response_model=CampaignOut)
async def analyze_campaign(
    data: CampaignCreate,
    current_user = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Starts the async AI Campaign Strategist generation pipeline."""
    campaign_id = str(uuid.uuid4())
    new_campaign = Campaign(
        id=campaign_id,
        user_id=current_user.id,
        website_url=data.website_url,
        product_url=data.product_url,
        product_description=data.product_description,
        brand_information=data.brand_information,
        target_audience=data.target_audience,
        campaign_goal=data.campaign_goal,
        status="queued"
    )
    db.add(new_campaign)
    await db.commit()
    await db.refresh(new_campaign)

    # Fire off Celery background task
    generate_full_campaign.delay(campaign_id)

    return new_campaign

@router.get("/history", response_model=List[CampaignOut])
async def get_campaign_history(
    current_user = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Returns a list of all campaigns generated by the user."""
    result = await db.execute(select(Campaign).filter(Campaign.user_id == current_user.id).order_by(Campaign.created_at.desc()))
    campaigns = result.scalars().all()
    return campaigns

@router.get("/{campaign_id}", response_model=CampaignFullOut)
async def get_campaign(
    campaign_id: str,
    current_user = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Returns the FULL campaign package with all nested elements."""
    result = await db.execute(select(Campaign).filter(Campaign.id == campaign_id, Campaign.user_id == current_user.id))
    campaign = result.scalars().first()
    if not campaign:
        raise HTTPException(status_code=404, detail="Campaign not found")

    # Fetch nested objects
    personas = (await db.execute(select(Persona).filter(Persona.campaign_id == campaign_id))).scalars().all()
    competitors = (await db.execute(select(CompetitorInsight).filter(CompetitorInsight.campaign_id == campaign_id))).scalars().all()
    angles = (await db.execute(select(Angle).filter(Angle.campaign_id == campaign_id))).scalars().all()
    hooks = (await db.execute(select(Hook).filter(Hook.campaign_id == campaign_id))).scalars().all()
    headlines = (await db.execute(select(Headline).filter(Headline.campaign_id == campaign_id))).scalars().all()
    ctas = (await db.execute(select(CTA).filter(CTA.campaign_id == campaign_id))).scalars().all()
    ad_copies = (await db.execute(select(AdCopy).filter(AdCopy.campaign_id == campaign_id))).scalars().all()
    concepts = (await db.execute(select(CreativeConcept).filter(CreativeConcept.campaign_id == campaign_id))).scalars().all()
    scripts = (await db.execute(select(VideoScript).filter(VideoScript.campaign_id == campaign_id))).scalars().all()
    scores = (await db.execute(select(CampaignScore).filter(CampaignScore.campaign_id == campaign_id))).scalars().all()

    # Construct full DTO
    full_campaign = CampaignFullOut.from_orm(campaign)
    full_campaign.personas = personas
    full_campaign.competitor_insights = competitors
    full_campaign.angles = angles
    full_campaign.hooks = hooks
    full_campaign.headlines = headlines
    full_campaign.ctas = ctas
    full_campaign.ad_copies = ad_copies
    full_campaign.creative_concepts = concepts
    full_campaign.video_scripts = scripts
    full_campaign.scores = scores

    return full_campaign
